version: "3.9"

services:
  gas-price-tracker:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - 8001:8000
    depends_on:
      - redis

  gas-price-tracker-daemon:
    image: ijonas/gas-price-tracker:0.0.1
    command: python main.py
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis/redis-stack-server
    ports:
      - 6379:6379
